apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ns-binder
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-ns-binder-cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-ns-binder
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ns-binder
  namespace: kube-system
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-ns-binder
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-ns-binder
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-ns-binder
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: ns-binder
        image: deinstapel/k8s-namespace-role-binding:latest
      serviceAccountName: {{ .Release.Name }}-ns-binder
