{{ $Values := .Values }}
{{ $Release := .Release }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "k8s-user-create-private-ns"
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - list
    - get
    - watch
    - create

---

{{- range $Values.users }}
# Generating service account for user '{{ .name }}'
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "k8s-user-{{ .name }}"
  namespace: kube-system
  labels:
    ds-user: "true"
  annotations:
    ds-username: "{{ .name }}"

---
{{- end }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "k8s-user-create-private-ns"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-user-create-private-ns
subjects:
{{- range $Values.users }}
- kind: ServiceAccount
  name: "k8s-user-{{ .name }}"
  namespace: kube-system
{{- end }}

